name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake files (Light)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vebkat   # <-- your username
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github   # shows months/weekdays

      - name: Generate Snake files (Dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: venkat-analytics
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark   # shows months/weekdays

      - name: Push Snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
