name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake with months & weekdays
        uses: Platane/snk@v3
        with:
          github_user_name: venkat-analytics
          outputs: |
            dist/snake-light.svg?palette=github
            dist/snake-dark.svg?palette=github-dark

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
