name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:      # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: venkat-analytics
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Add axes labels (months, weekdays, year) to SVGs
        run: |
          python3 - <<'EOF'
          import xml.etree.ElementTree as ET
          from datetime import datetime

          CELL = 13
          START_X = 16
          START_Y = 16

          def add_labels(svg_file, text_color="gray"):
              tree = ET.parse(svg_file)
              root = tree.getroot()

              # Put labels inside <g> layer on top so they are visible
              g = ET.Element("g")

              # Add year label (top left)
              year = str(datetime.now().year)
              year_text = ET.Element("text", {
                  "x": str(START_X),
                  "y": str(START_Y - 8),
                  "fill": text_color,
                  "font-size": "12",
                  "font-family": "sans-serif",
                  "font-weight": "bold"
              })
              year_text.text = year
              g.append(year_text)

              # Add weekdays (Mon, Wed, Fri)
              weekdays = ["Mon", "Wed", "Fri"]
              for i, day in enumerate([1, 3, 5]):
                  text = ET.Element("text", {
                      "x": str(START_X - 30),
                      "y": str(START_Y + CELL*day + 9),
                      "fill": text_color,
                      "font-size": "10",
                      "font-family": "sans-serif"
                  })
                  text.text = weekdays[i]
                  g.append(text)

              # Add months (every ~4 weeks across top)
              months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
              for i, month in enumerate(months):
                  text = ET.Element("text", {
                      "x": str(START_X + i*CELL*4),
                      "y": str(START_Y - 8),
                      "fill": text_color,
                      "font-size": "10",
                      "font-family": "sans-serif"
                  })
                  text.text = month
                  g.append(text)

              root.append(g)  # append as last so it's drawn on top
              tree.write(svg_file)

          # Light SVG
          add_labels("dist/github-contribution-grid-snake.svg", "gray")
          # Dark SVG
          add_labels("dist/github-contribution-grid-snake-dark.svg", "white")
          EOF

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
