name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:      # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: venkat-analytics
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 🔎 Debug step to inspect SVG structure
      - name: Debug Snake SVG structure
        run: |
          python3 - <<'EOF'
          import xml.etree.ElementTree as ET

          svg_file = "dist/github-contribution-grid-snake.svg"
          tree = ET.parse(svg_file)
          root = tree.getroot()

          print("=== SVG Root Attributes ===")
          print(root.attrib)

          print("\n=== First 10 Rectangles (contribution cells) ===")
          rects = root.findall(".//{http://www.w3.org/2000/svg}rect")
          for i, rect in enumerate(rects[:10]):
              print(rect.attrib)

          print(f"\nTotal contribution cells: {len(rects)}")
          EOF

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
