name: Generate Snake  

on:  
  schedule:  
    - cron: "0 0 * * *"   # runs every day at midnight  
  workflow_dispatch:  

permissions:  
  contents: write  

jobs:  
  generate:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Generate Snake  
        uses: Platane/snk/svg-only@v3  
        with:  
          github_user_name: venkat-analytics  
          outputs: |  
            dist/github-contribution-grid-snake.svg  
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  

      - name: Add axes labels (months, weekdays, year) to SVGs  
        run: |  
          python3 <<'EOF'  
          import xml.etree.ElementTree as ET  
          from datetime import datetime  

          CELL = 12     # grid cell size (10px + 2px gap)  
          START_X = 14  # grid start x  
          START_Y = 14  # grid start y  
          def add_labels(svg_file):  
              tree = ET.parse(svg_file)  
              root = tree.getroot()  

              # Add year  
              year = str(datetime.now().year)  
              text = ET.Element("text", {  
                  "x": str(START_X), "y": str(START_Y - 6),  
                  "fill": "gray", "font-size": "12",  
                  "font-family": "sans-serif"  
              })  
              text.text = year  
              root.append(text)  

              # Add weekdays (Mon, Wed, Fri)  
              weekdays = ["Mon", "Wed", "Fri"]  
              for i, day in enumerate([1, 3, 5]):  
                  text = ET.Element("text", {  
                      "x": str(START_X - 22),  
                      "y": str(START_Y + CELL*day + 8),  
                      "fill": "gray", "font-size": "10",  
                      "font-family": "sans-serif"  
                  })  
                  text.text = weekdays[i]  
                  root.append(text)  

              # Add months (every 4 weeks ≈ 28 days)  
              months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]  
              for i, month in enumerate(months):  
                  text = ET.Element("text", {  
                      "x": str(START_X + i*CELL*4),  
                      "y": str(START_Y - 4),  
                      "fill": "gray", "font-size": "10",  
                      "font-family": "sans-serif"  
                  })  
                  text.text = month  
                  root.append(text)  

           tree.write(svg_file)  

          # Apply to both SVGs  
          add_labels("dist/github-contribution-grid-snake.svg")  
          add_labels("dist/github-contribution-grid-snake-dark.svg")  
          EOF  

      - name: Push Snake to output branch  
        uses: crazy-max/ghaction-github-pages@v3.1.0  
        with:  
          target_branch: output  
          build_dir: dist  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
