name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate snake SVGs
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: venkat-analytics
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 3: Add axis labels (months, weekdays, year)
      - name: Add Labels to Snake
        run: |
          python3 - <<'EOF'
          import xml.etree.ElementTree as ET
          from datetime import datetime

          for file in ["dist/github-contribution-grid-snake.svg",
                       "dist/github-contribution-grid-snake-dark.svg"]:
              tree = ET.parse(file)
              root = tree.getroot()
              ns = {"svg": "http://www.w3.org/2000/svg"}

              # Add months (top axis)
              months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
              start_x, y, step = 14, 10, 60
              for i, month in enumerate(months):
                  text = ET.Element("text", {
                      "x": str(start_x + i*step),
                      "y": str(y),
                      "font-size": "10",
                      "fill": "#555",
                      "text-anchor": "middle"
                  })
                  text.text = month
                  root.append(text)

              # Add weekdays (left axis)
              weekdays = ["Mon","Wed","Fri"]
              x, start_y, step = 2, 24, 26
              for i, day in enumerate(weekdays):
                  text = ET.Element("text", {
                      "x": str(x),
                      "y": str(start_y + i*step),
                      "font-size": "10",
                      "fill": "#555",
                      "text-anchor": "start"
                  })
                  text.text = day
                  root.append(text)

              # Add current year (bottom center)
              year = str(datetime.now().year)
              text = ET.Element("text", {
                  "x": "360",  # half of 720 width
                  "y": "105",  # near bottom
                  "font-size": "12",
                  "fill": "#333",
                  "text-anchor": "middle",
                  "font-weight": "bold"
              })
              text.text = year
              root.append(text)

              tree.write(file)
          EOF

      # Step 4: Push snake to output branch
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
